### ISSUE TITLE
Unable to receive/cache rest requests

### ISSUE THREAD

**Issue by thieleju** [kb-coder/vue-cli-plugin-workbox-pwa#3]
Hi, 
my colleague and I are trying to get our vue project to cache GET requests with your package (In this example `/apps`).

Caching styles, scripts, images and so on works perfectly fine out of the box. 

Steps to reproduce:
1. Created new vue project with `vue create pwatest`
    - Babel, PWA Support, Router, CSS Pre-processors, Linter
    - Version 2.x, history mode: yes, sass/scss, ESLint + Prettier

2. `vue add workbox-pwa`
    - chose `Inject Manifest`
    - `vue.config.js` is default
3. Added the following in `sw.js`:
```js
registerRoute(
  ({ url }) => url.pathname.includes("/apps"),
  new StaleWhileRevalidate({
    cacheName: "rest",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [200],
      }),
    ],
  })
);
```
4. Run `npm run pwa-serve`

We tried every strategy, but everytime the service worker is active and the ´/apps´ request is sent, it fails.

 ![image](https://user-images.githubusercontent.com/41455100/162933056-dc46958a-245d-4fe4-8888-faa78bf1486f.png)

This is our log

![image](https://user-images.githubusercontent.com/41455100/162930864-529256ae-bee5-4601-b2d8-f757d3649d63.png)

<details>

  <summary>Show package.json</summary>

```json
  {
    "name": "pwatest",
    "version": "0.1.0",
    "private": true,
    "scripts": {
      "serve": "vue-cli-service serve",
      "build": "vue-cli-service build",
      "lint": "vue-cli-service lint",
      "pwa-build": "vue-cli-service build --mode pwalocalserve",
      "pwa-serve": "npm run pwa-build && serve -s dist -l 8080"
    },
    "dependencies": {
      "axios": "^0.26.1",
      "core-js": "^3.8.3",
      "register-service-worker": "^1.7.2",
      "vue": "^2.6.14",
      "vue-router": "^3.5.1",
      "workbox-cacheable-response": "^6.1.5",
      "workbox-core": "^6.1.5",
      "workbox-expiration": "^6.1.5",
      "workbox-precaching": "^6.1.5",
      "workbox-routing": "^6.1.5",
      "workbox-strategies": "^6.1.5",
      "workbox-window": "^6.1.5"
    },
    "devDependencies": {
      "@babel/core": "^7.12.16",
      "@babel/eslint-parser": "^7.12.16",
      "@vue/cli-plugin-babel": "~5.0.0",
      "@vue/cli-plugin-eslint": "~5.0.0",
      "@vue/cli-plugin-pwa": "~5.0.0",
      "@vue/cli-plugin-router": "~5.0.0",
      "@vue/cli-service": "~5.0.0",
      "eslint": "^7.32.0",
      "eslint-config-prettier": "^8.3.0",
      "eslint-plugin-prettier": "^4.0.0",
      "eslint-plugin-vue": "^8.0.3",
      "prettier": "^2.4.1",
      "sass": "^1.32.7",
      "sass-loader": "^12.0.0",
      "vue-cli-plugin-workbox-pwa": "~0.1.3",
      "vue-template-compiler": "^2.6.14",
      "workbox-webpack-plugin": "^6.1.5"
    }
  }
```

</details>

Do you know what we're doing wrong?

**Comment by kb-coder** [comment]
This plugin is provided as is. It is intended for use with Vue 3 and not Vue 2. You are welcome to fork the repo and adjust the plugin as you see fit.

**Comment by thieleju** [comment]
Okay that explains it, thank you for the quick response
